### ISSUE TITLE
sabnzbd - metrics values

### ISSUE THREAD

**Issue by reefland** [onedr0p/exportarr#148]
Saw reference to `sabnzbd` metrics being available in latest version.  Working on a Grafana Dashboard for it, but having some issues with 2 metrics:

* `sabnzbd_disk_total_bytes` seems to be reporting size in number of 1K blocks not bytes.  I get `209715200` 1K blocks instead of `214748364800` bytes.

* `sabnzbd_disk_used_bytes` not sure what its reporting as it shows up as a decimal such `207901163.52`. I'm expecting more like `1855259765` bytes (reported by `du -b /downloads`).  Value reported seems closer to free space in 1K blocks `207904768` than used space in bytes.

**Comment by rtrox** [comment]
Gah, this is likely a casualty of me collapsing the parsing logic into the UnmarshalJSON method when I pulled this in. The Sabnzbd API uses different approaches to different metrics -- some dynamically set the unit, others are pinned to KB or MB, and others are in bytes. I thought I had unit tests on these to make sure the unit was right, but it looks like I missed some of them. Will look at this later tonight, should be a quick fix.

**Comment by rtrox** [comment]
PR is up for this -- it turns out this behavior was incorrect before pulling it in to exportarr as well. These metrics come back from the SAB API in GB, where the amount of data remaining to download is expressed in MB, and bandwidth is expressed in kbps. I think these should now all be getting correctly parsed, but let me know if you find any other metrics that look off.
