### ISSUE TITLE
Sabnzbd - something wacky with download rate metric 

### ISSUE THREAD

**Issue by reefland** [onedr0p/exportarr#176]
exportarr: `v1.4.0` / sabnzbd: `4.0.1`

@rtrox - For Sabnzb dashboard `Download Rate` I'm using this to drive that panel: `avg(increase(sabnzbd_server_downloaded_bytes[$__rate_interval])) by (server)` with unit `bytes/sec(IEC)`

![image](https://github.com/onedr0p/exportarr/assets/16230914/b2e84cc6-ced5-4280-bc1a-0d795eb3649a)

There is no way that test was grabbing at over 8Gib/Sec when the network total for that container was under 100Mib/sec.  Any ideas on what's the proper metric to use for that panel?

**Comment by rtrox** [comment]
@reefland - you probably want `rate` or `irate` instead of `increase`. I think you probably took that from the dashboard I initially created, I need to update it - my scrape interval was set to 1 sec during development, so `increase` and `{i,}rate` were identical.

`increase` - creates a datapoint which is the difference between the current raw data point and the one prior. So if the datapoints are 5 seconds apart, or 30 seconds apart, it will count the full difference.
`rate` - extrapolates the average per second rate of the metric. So if the datapoints are 1 second apart, its the same as `increase`. If they're 5 seconds apart, it calculates the differences and divides by 5.

**Comment by reefland** [comment]
@rtrox - awesome thanks.  This look much better now:

![image](https://github.com/onedr0p/exportarr/assets/16230914/e362433e-dd36-4341-b1c6-f1070a2dd583)

I'll submit a PR in a few days.

**Comment by reefland** [comment]
Went to submit a PR but needed to account for #173 .  However, that PR completely broke all single instance dashboard for me (see my comment on that PR).  Not sure if I should open a new defect on that or not.  Anyway, submitting this fix is on hold until that is resolved as the dashboard is not testable for me at the moment.

**Comment by rtrox** [comment]
@reefland makes sense -- cc @Kariton - please let me know if you're able to prioritize resolving the bug on #173. If not, in a couple days I can either back it out or fix it.

**Comment by reefland** [comment]
@Kariton - Were you able to work on this?

**Comment by Kariton** [comment]
Hello,

TBH i dont know how this happened...
i have more then one dashboard with repeating where i use the `=~` operator.
but for some reason, while updating the dasboard, a simple `=` worked for me.

i have opened PR https://github.com/onedr0p/exportarr/pull/192 to fix this. but i currently dont have any data for my stack to really test this...

**Comment by reefland** [comment]
@Kariton - Did you see my comments I left on #192.  It's better but still has some issues.
