### ISSUE TITLE
Multi-instance dashboard issues.

### ISSUE THREAD

**Issue by reefland** [onedr0p/exportarr#193]
Testing multi-instance dashboard fix in #192 which worked mostly except for:

1. `sabnzbd` always returned no instances.  I tracked this down to a misspelling in the instance variable.  instead of  `bd` it is using `db` which is backwards.  Should be `{__name__=~"sabnzbd_.*"}` not `{__name__=~"sabnzdb_.*"}`.

2. All instance variables are set to refresh only on dashboard load only.  If you change the time range using the date picker in the dashboard, the number of instances running during the new time range is not updated.

3. The version number within the dashboard yaml was not bumped.  (it's the 3rd line from the bottom of the file).

I'll submit a PR to address these issues.

**Comment by Kariton** [comment]
Hey @reefland,
1. That typo was a nice catch. damn it...
i just wanted to check if i maybe did set the datasource hardcoded and did not use the proper variable `${DS_PROMETHEUS}`

2. i never have had / experienced that as problem with "on load" variables but that is a interesting situation.
mainly because i dont go back in time were stuff like this matters.
i also never considered "on time change" because it will also refresh those variables on every "auto reload" which might create a "unnecessary" load to small instances (like RPis and such) and could cause timeouts. i have experienced that in the past, on more complex dashboards and variables though.

thank you for investigating those issues!
