### ISSUE TITLE
Sonarr API V3 = ENABLE_ADDITIONAL_METRICS and Qualities

### ISSUE THREAD

**Issue by Snusel** [onedr0p/exportarr#266]
# Details

Hello, I'm wondering why --enable-additional-metrics is so slow and why, according to the log file, the extra data is always from

HTTP request {"url": "URL/api/v3/episode?seriesId=ID"}

HTTP request {"url": "URL/api/v3/episodefile?seriesId=ID"}

be retrieved

And not directly from
Quality definition
Quality Profile
QualityProfileSchema

Because I think it's faster than the current method

Because Sonarr has already collected the information and put it in a database
Sqlite 3.44.2 Saved

Because I've been running it for 18 hours now and I still don't have any qualities information in prometheus and grafana

(https://sonarr.tv/docs/api/#/)

QualityDefinition
QualityProfile
QualityProfileSchema

![chrome_AFCjpBY2Ua](https://github.com/onedr0p/exportarr/assets/10830942/2c206eea-0cbd-4a90-8694-79cb68f22c86)

**Comment by rtrox** [comment]
Unfortuntely, the API Endpoints that you call out here don't actually have the info needed to populate the quality info :-/ The Quality Definitions endpoints only give you the definitions themselves, and the Profiles endpoints only give you the profiles themselves. Examples of each:
```
## Definition
❯ curl -H "X-Api-Key: $SONARR_API_KEY" https://${ENDPOINT}/api/v3/qualitydefinition/21
{
  "quality": {
    "id": 21,
    "name": "Bluray-2160p Remux",
    "source": "blurayRaw",
    "resolution": 2160
  },
  "title": "Bluray-2160p Remux",
  "weight": 17,
  "minSize": 187.4,
  "id": 21
}
```

vs Profile:
```
❯ curl -H "X-Api-Key: $SONARR_API_KEY" https://sonarr.rtrox.io/api/v3/qualityprofile | head -n 100
  {
    "name": "WEB-1080p",
    "upgradeAllowed": true,
    "cutoff": 1002,
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown",
          "source": "unknown",
          "resolution": 0
        },
        "items": [],
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV",
 ...
 ```
 So unfortunately, those endpoints won't work, we have to get them from the episodes themselves in order to build counts of episodes per profile. 
 
 That said, this is specifically why the `--enable-additional-metrics` flag exists, is to gate off the expensive calls needed to populate quality info. I'd recommend that if you have too many episodes for exportarr to return during your scrape timeout, that you either A) disable the additional metrics, or B) increase your scrape timeout.
