### ISSUE TITLE
Integrate Bazarr

### ISSUE THREAD

**Issue by rubasace** [onedr0p/exportarr#6]
Hi, it's your biggest fan again. I like this new approach of centralizing everything :)

I think it would be nice to have also metrics for bazarr :)

**Comment by onedr0p** [comment]
I also use Bazarr but I've always felt it is super janky (my exact feelings for Ombi too). Bazarr is not written in the stack as Sonarr/Radarr/Lidarr (the dev just copied the v2 UI of Sonarr and wrote it in Python). Also, I don't even know if it has a API. Not sure if I'll get to this anytime soon, but that being said I'll leave this issue open if my opinion ever changes.

Feel free to poke me with more information if you find out more info on Bazarr and it's API.

**Comment by rubasace** [comment]
Oh, I see. I was just driven by the UI, as it looks the same :)

I'll do some investigation and let you know

**Comment by kinduff** [comment]
There's an undocumented API https://github.com/morpheus65535/bazarr/blob/master/bazarr/api.py (actual), The upcoming one: https://github.com/morpheus65535/bazarr/blob/frontend-upgrade/bazarr/api.py (upcoming). 

Same feeling, feels janky. I like what some apps do that instead of integrating Bazarr as is, they integrate some data with Sonarr and Radarr, like complementing the data.

**Comment by onedr0p** [comment]
I am going to close this issue as I feel it is out of scope for this exporter. If there is any interests in someone PRing it I might reconsider.

**Comment by phyzical** [comment]
no promises, but if i get time i've been looking for an excuse to play with this side of metrics

had a quick chat to the maintainer, https://github.com/morpheus65535/bazarr/blob/master/bazarr/api/history/stats.py is what he suggested as a starting point but they didn't have any real plans around supporting it their side.
