### ISSUE TITLE
Rename the metric lidarr_songs_missing_total

### ISSUE THREAD

**Issue by ngosang** [onedr0p/exportarr#82]
The metric `lidarr_songs_missing_total` should be called `lidarr_albums_missing_total`

My config:
* Exportarr v1.1.0
* Sonarr 3.0.8.1507
* Radarr 4.1.0.6175
* Lidarr 1.0.2.2592

**Comment by rtrox** [comment]
I don't personally use `lidarr` so I can't verify this -- can someone share their `/api/v1/wanted/missing` endpoint output, as well as the number of songs & albums that they expected to be "missing"?

You should be able to:
```
curl https://your.lidarr.deploy/api/v1/wanted/missing -H "X-Api-Key: <yourapikey>"
```

That would be what I need to verify & fix. otherwise, definitely open to a PR

**Comment by rtrox** [comment]
nvm, @onedr0p beat me to it :-D

**Comment by ngosang** [comment]
Thank you!
